name: CI Pipeline

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASS }}
      DB_URL: ${{ secrets.DB_URL }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Liquibase Docker image
        run: |
          docker build -f ${{ github.workspace }}/liquibase/Dockerfile.liquibase -t my-liquibase .

      - name: Run Liquibase history using liquibase.docker.properties
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase/changelog:/liquibase/changelog \
            --env DB_USERNAME \
            --env DB_PASSWORD \
            --env DB_URL \
            my-liquibase --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} history
