name: CI Pipeline

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASS }}
      DB_URL: ${{ secrets.DB_URL }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Liquibase Docker image
        run: |
          docker build -f ${{ github.workspace }}/liquibase/Dockerfile.liquibase -t my-liquibase .

      - name: Run changelog-sync with changelog-baseline
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase/changelog:/liquibase/changelog \
            -w /liquibase/changelog \
            my-liquibase --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} --defaults-file=/liquibase/liquibase.docker.properties changelog-sync
      
      - name: List generated files for troubleshooting
        run: ls -l liquibase/changelog/
      
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: liquibase-changelog
          path: liquibase/changelog/generated_changelogs/changelog.xml

