name: CI Pipeline

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Liquibase Docker Image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase:/liquibase/changelog \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            my-liquibase \
            bash -c "liquibase \
              --url='jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=your-host)(PORT=2484))(CONNECT_DATA=(SID=ORACLE)))' \
              --username=$DB_USER \
              --password=$DB_PASS \
              --changeLogFile=changelog/changelog.xml \
              history"

