name: CI Pipeline

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Liquibase Docker image
        run: |
          docker build -f ${{ github.workspace }}/liquibase/Dockerfile.liquibase -t my-liquibase .

      - name: Run Liquibase history using liquibase.docker.properties
        run: |
          docker run --rm \
            -e username=${{ secrets.DB_USER }} \
            -e password=${{ secrets.DB_PASS }} \
            my-liquibase \
            history
