name: CI Pipeline

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Liquibase Docker Image
        run: |
          docker build -f ${{ github.workspace }}/liquibase/Dockerfile.liquibase -t my-liquibase .
        
      - name: Run Liquibase update using custom image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase:/liquibase/changelog \
            my-liquibase \
            --url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=database-1.cajekgz96o6t.us-east-1.rds.amazonaws.com)(PORT=2484))(CONNECT_DATA=(SID=ORACLE))) \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASS }} \
            --changeLogFile=changelog/changelog.xml \
            history